import { useState } from "react";
import { Download, Share2, Database, FileJson, X, Copy, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { toast } from "sonner";
import { cn } from "@/components/ui/utils";

interface ComplianceActionsProps {
  reportData?: any;
  fileNamePrefix?: string;
  hideHeader?: boolean;
  className?: string;
}

const ComplianceActions = ({
  reportData,
  fileNamePrefix = "COI_Report",
  hideHeader = false,
  className
}: ComplianceActionsProps) => {
  const [showRawData, setShowRawData] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleDownloadPDF = () => {
    if (!reportData) {
      toast.error("No data to download");
      return;
    }

    toast.loading("Generating PDF Report...");

    try {
      // Capture Graph SVG if available
      let graphHtml = "";
      const svgElement = document.getElementById('coi-relationship-graph-svg');
      if (svgElement) {
        // Clone to avoid modifying the live graph
        const clone = svgElement.cloneNode(true) as SVGElement;
        // Reset transform to ensure it fits on paper
        clone.style.transform = "scale(1)";
        clone.style.width = "100%";
        clone.style.height = "auto";
        clone.style.maxHeight = "400px";
        graphHtml = `
          <div class="section" style="text-align: center;">
            <h2>Relationship Graph</h2>
            <div style="border: 1px solid #ddd; padding: 10px; border-radius: 8px;">
              ${clone.outerHTML}
            </div>
          </div>
        `;
      }

      // Create a printable HTML representation
      const content = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>${fileNamePrefix}</title>
          <style>
            body { font-family: sans-serif; padding: 40px; color: #333; }
            h1 { border-bottom: 2px solid #333; padding-bottom: 10px; }
            .meta { color: #666; font-size: 0.9em; margin-bottom: 30px; }
            .section { margin-bottom: 30px; padding: 20px; background: #f9f9f9; border-radius: 8px; page-break-inside: avoid; }
            .conflict { padding: 10px; border-left: 4px solid #ef4444; background: white; margin-top: 10px; }
            .safe { color: #10b981; font-weight: bold; }
            .risk { color: #ef4444; font-weight: bold; }
          </style>
        </head>
        <body>
          <h1>Conflict of Interest Report</h1>
          <div class="meta">
            <p><strong>Date:</strong> ${new Date().toLocaleString()}</p>
            <p><strong>Report ID:</strong> ${fileNamePrefix}</p>
            <p><strong>Generated By:</strong> Institutional Conflict Check System</p>
          </div>

          <div class="section">
            <h2>Analysis Summary</h2>
            <p><strong>Investor:</strong> ${reportData.investorName || "N/A"}</p>
            <p><strong>Target Company:</strong> ${reportData.targetCompany || "N/A"}</p>
            <p><strong>Status:</strong> ${reportData.hasConflict ? '<span class="risk">CONFLICT DETECTED</span>' : '<span class="safe">NO CONFLICT FOUND</span>'}</p>
            <p><strong>Risk Level:</strong> Level ${reportData.conflictLevel || 0}</p>
          </div>

          ${graphHtml}

          ${reportData.hasConflict ? `
            <div class="section">
              <h2>Detected Conflicts</h2>
              ${reportData.conflictLevel === 2 ?
            (reportData.conflicts || []).map((c: any) => `
                  <div class="conflict">
                    <p><strong>Type:</strong> Subsidiary / Competitor (Level 2)</p>
                    <p>Parent '${c.investedParent}' owns '${c.competingSubsidiary}' which competes with the target.</p>
                  </div>
                `).join('')
            :
            (reportData.conflictingCompanies || []).map((c: string) => `
                  <div class="conflict">
                    <p><strong>Type:</strong> Sector Overlap (Level 1)</p>
                    <p>Portfolio company '${c}' operates in the same domain as the target.</p>
                  </div>
                `).join('')
          }
            </div>
          ` : ''}

          <div class="section">
            <h2>Compliance Recommendations</h2>
            <ul>
              ${reportData.hasConflict ?
          `<li>Initiate formal review process.</li>
                 <li>Consult legal team regarding specific overlaps.</li>
                 <li>Document all findings in the central registry.</li>`
          :
          `<li>Proceed with standard due diligence.</li>
                 <li>Log this check for audit purposes.</li>`
        }
            </ul>
          </div>
          
          <script>
            window.onload = function() { window.print(); }
          </script>
        </body>
        </html>
      `;

      const blob = new Blob([content], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const printWindow = window.open(url, '_blank');

      // Cleanup
      if (printWindow) {
        printWindow.onafterprint = () => {
          URL.revokeObjectURL(url);
        };
      }

      toast.dismiss();
      toast.success("Ready to print/save as PDF");

    } catch (e) {
      console.error(e);
      toast.error("Failed to generate report");
    }
  };

  const handleExportGraph = () => {
    if (!reportData) return;

    // Construct a JSON representation of the graph
    const graphData = {
      meta: {
        investor: reportData.investorName,
        target: reportData.targetCompany,
        generatedAt: new Date().toISOString()
      },
      nodes: [
        { id: "inv", label: reportData.investorName, type: "investor" },
        { id: "tgt", label: reportData.targetCompany, type: "target" }
      ],
      edges: [] as any[]
    };

    if (reportData.conflictLevel === 1 && reportData.conflictingCompanies) {
      reportData.conflictingCompanies.slice(0, 10).forEach((comp: string, i: number) => {
        const id = `l1-${i}`;
        graphData.nodes.push({ id, label: comp, type: "company" });
        graphData.edges.push({ from: "inv", to: id, relation: "invested_in" });
        graphData.edges.push({ from: id, to: "tgt", relation: "competes_with_sector" });
      });
    } else if (reportData.conflictLevel === 2 && reportData.conflicts) {
      reportData.conflicts.forEach((c: any, i: number) => {
        const pid = `p-${i}`;
        const sid = `s-${i}`;
        graphData.nodes.push({ id: pid, label: c.investedParent, type: "company" });
        graphData.nodes.push({ id: sid, label: c.competingSubsidiary, type: "company" });
        graphData.edges.push({ from: "inv", to: pid, relation: "invested_in" });
        graphData.edges.push({ from: pid, to: sid, relation: "owns" });
        graphData.edges.push({ from: sid, to: "tgt", relation: "competes_with" });
      });
    }

    const blob = new Blob([JSON.stringify(graphData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${fileNamePrefix}_graph.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    toast.success("Graph Data Exported", {
      description: "Relationship data saved as JSON.",
    });
  };

  const handleCopyRaw = () => {
    if (reportData) {
      navigator.clipboard.writeText(JSON.stringify(reportData, null, 2));
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      toast.success("Copied to clipboard");
    }
  };

  return (
    <>
      <Card className={cn("animate-fade-in bg-white border-border rounded-[2.5rem] shadow-sm overflow-hidden p-4", className)}>
        {!hideHeader && (
          <CardHeader className="pb-3 p-6">
            <CardTitle className="flex items-center gap-3 text-xl font-bold">
              <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-primary/10">
                <Share2 className="h-5 w-5 text-primary" />
              </div>
              Compliance Actions
            </CardTitle>
          </CardHeader>
        )}

        <CardContent className="px-6 pb-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <Button
              variant="default"
              onClick={handleDownloadPDF}
              className="w-full h-14 rounded-2xl font-bold text-sm shadow-md hover:scale-[1.02] transition-transform flex items-center justify-center gap-3"
            >
              <Download className="h-5 w-5" />
              Download PDF Report
            </Button>

            <Button
              variant="outline"
              onClick={handleExportGraph}
              className="w-full h-14 rounded-2xl font-bold text-sm border-2 border-primary/20 text-primary hover:bg-primary/5 hover:scale-[1.02] transition-transform flex items-center justify-center gap-3"
            >
              <Share2 className="h-5 w-5" />
              Export Graph Data
            </Button>

            <Button
              variant="secondary"
              onClick={() => setShowRawData(true)}
              className="w-full h-14 rounded-2xl font-bold text-sm bg-secondary/50 text-foreground hover:bg-secondary hover:scale-[1.02] transition-transform flex items-center justify-center gap-3"
            >
              <FileJson className="h-5 w-5" />
              View Raw Data
            </Button>
          </div>

          <div className="mt-6 flex items-center gap-4 p-5 rounded-[1.5rem] bg-[#F8FAFC] border border-border/50">
            <div className="w-10 h-10 rounded-xl bg-white flex items-center justify-center shadow-sm shrink-0">
              <Database className="h-5 w-5 text-primary" />
            </div>
            <p className="text-xs text-muted-foreground font-medium leading-relaxed">
              All reports are <span className="text-foreground font-bold underline decoration-primary/20">timestamped and logged</span> for audit compliance.
              Data retention is maintained for <span className="text-foreground font-bold">7 years</span>.
            </p>
          </div>
        </CardContent>
      </Card>

      {/* Raw Data Dialog */}
      <Dialog open={showRawData} onOpenChange={setShowRawData}>
        <DialogContent className="max-w-3xl max-h-[80vh] overflow-hidden flex flex-col rounded-3xl">
          <DialogHeader>
            <DialogTitle>Raw Analysis Data</DialogTitle>
            <DialogDescription>
              Complete JSON response from the conflict engine.
            </DialogDescription>
          </DialogHeader>

          <div className="flex-1 overflow-auto bg-slate-950 p-4 rounded-xl relative group">
            <Button
              size="icon"
              variant="ghost"
              className="absolute top-2 right-2 text-slate-400 hover:text-white bg-slate-900/50 hover:bg-slate-800"
              onClick={handleCopyRaw}
            >
              {copied ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
            </Button>
            <pre className="text-xs font-mono text-green-400 whitespace-pre-wrap break-all">
              {JSON.stringify(reportData, null, 2)}
            </pre>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
};

export default ComplianceActions;
